
package view.Phieu;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import model.ChiTietDon;
import model.HoaDon;

/**
 *
 * @author MeoMeo
 */
public class hoaDonForm extends javax.swing.JFrame {

    
    
    public hoaDonForm(HoaDon hd) { 
        initComponents();
        this.setSize(424, 604);
        this.setLocationRelativeTo(null);
        chietKhauField.setText(hd.getChietKhau() + "%");
        tenKH.setText(hd.getKhachHang().getTen());
        maHoaDon.setText(hd.getMa());
        nvBH.setText(hd.getNhanVien().getTen());
        billDate.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        int tong = hd.getTien();
        totalCost.setText(tong + "");
        ArrayList<ChiTietDon> ds = hd.getDsBanh();
        DefaultTableModel bang = new DefaultTableModel(new String[] {"Mã bánh", "Tên bánh", "Đơn giá", "Số lượng", "Tổng"}, ds.size());
        int cow = 0;
        bangchitiet.setModel(bang);
        for( ChiTietDon c : ds){
           bang.setValueAt(c.getBanh().getMa(), cow, 0);
           bang.setValueAt(c.getBanh().getTen(), cow, 1);
           bang.setValueAt(c.getBanh().getGia(), cow, 2);
           bang.setValueAt(c.getSoluong(), cow, 3);
           bang.setValueAt(c.getTien(), cow, 4);
           cow++;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangchitiet = new javax.swing.JTable();
        billDate = new javax.swing.JTextField();
        maHoaDon = new javax.swing.JTextField();
        tenKH = new javax.swing.JTextField();
        nvBH = new javax.swing.JTextField();
        totalCost = new javax.swing.JTextField();
        tathoadon = new javax.swing.JButton();
        chietKhauField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(46, 68, 84));
        setMinimumSize(new java.awt.Dimension(424, 604));
        setUndecorated(true);
        getContentPane().setLayout(null);

        bangchitiet.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bangchitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        bangchitiet.setColumnSelectionAllowed(true);
        bangchitiet.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bangchitiet.setFillsViewportHeight(true);
        bangchitiet.setGridColor(new java.awt.Color(0, 0, 0));
        bangchitiet.setIntercellSpacing(new java.awt.Dimension(2, 2));
        bangchitiet.setPreferredSize(new java.awt.Dimension(300, 66));
        bangchitiet.setRowHeight(20);
        bangchitiet.setSelectionBackground(new java.awt.Color(51, 51, 255));
        jScrollPane1.setViewportView(bangchitiet);
        bangchitiet.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(-10, 190, 440, 250);

        billDate.setEditable(false);
        billDate.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        billDate.setText("dd/mm/yyy");
        billDate.setBorder(null);
        billDate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        billDate.setOpaque(false);
        getContentPane().add(billDate);
        billDate.setBounds(40, 480, 170, 30);

        maHoaDon.setEditable(false);
        maHoaDon.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        maHoaDon.setForeground(new java.awt.Color(239, 61, 49));
        maHoaDon.setText("01");
        maHoaDon.setBorder(null);
        maHoaDon.setDisabledTextColor(new java.awt.Color(239, 61, 49));
        maHoaDon.setOpaque(false);
        getContentPane().add(maHoaDon);
        maHoaDon.setBounds(230, 140, 170, 30);

        tenKH.setEditable(false);
        tenKH.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tenKH.setForeground(new java.awt.Color(239, 61, 49));
        tenKH.setText("Teennnn ");
        tenKH.setBorder(null);
        tenKH.setDisabledTextColor(new java.awt.Color(239, 61, 49));
        tenKH.setOpaque(false);
        getContentPane().add(tenKH);
        tenKH.setBounds(30, 140, 190, 20);

        nvBH.setEditable(false);
        nvBH.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        nvBH.setText("Name");
        nvBH.setBorder(null);
        nvBH.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        nvBH.setOpaque(false);
        getContentPane().add(nvBH);
        nvBH.setBounds(290, 160, 130, 30);

        totalCost.setEditable(false);
        totalCost.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        totalCost.setForeground(new java.awt.Color(239, 61, 49));
        totalCost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalCost.setText("Cost");
        totalCost.setBorder(null);
        totalCost.setDisabledTextColor(new java.awt.Color(239, 61, 49));
        totalCost.setOpaque(false);
        getContentPane().add(totalCost);
        totalCost.setBounds(220, 480, 170, 30);

        tathoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/closeButtonForSmallOb.png"))); // NOI18N
        tathoadon.setBorderPainted(false);
        tathoadon.setContentAreaFilled(false);
        tathoadon.setFocusPainted(false);
        tathoadon.setFocusable(false);
        tathoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tathoadonMouseClicked(evt);
            }
        });
        getContentPane().add(tathoadon);
        tathoadon.setBounds(380, 10, 40, 23);

        chietKhauField.setEditable(false);
        chietKhauField.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        chietKhauField.setBorder(null);
        chietKhauField.setCaretColor(new java.awt.Color(255, 255, 255));
        chietKhauField.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        chietKhauField.setOpaque(false);
        getContentPane().add(chietKhauField);
        chietKhauField.setBounds(90, 170, 120, 10);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel1.setText("Chiết khấu:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 170, 60, 13);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Borreder/BillForm.png"))); // NOI18N
        BG.setOpaque(true);
        getContentPane().add(BG);
        BG.setBounds(0, 0, 424, 604);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tathoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tathoadonMouseClicked
        this.dispose();
      //  view.NhanVien.NhanVienForm.formNV.setVisible(true);
    }//GEN-LAST:event_tathoadonMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(hoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(hoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(hoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(hoaDonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                java.sql.Connection con = controller.ConnectDB.getConnection();
//                ArrayList<HoaDon> ds = controller.AccessData.loadListHoaDon("2019-11-17", con);
//                ArrayList<ChiTietDon> dsb = new ArrayList<>();
//                dsb.add(new ChiTietDon(controller.AccessData.findBanhMi("B1", con), 11));
//                new hoaDonForm(new HoaDon("2300000000000", controller.AccessData.findNhanVien("NV1", con), controller.AccessData.findKhachHang("0866785501",  con), dsb, 0, new Date())).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JTable bangchitiet;
    private javax.swing.JTextField billDate;
    private javax.swing.JTextField chietKhauField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField maHoaDon;
    private javax.swing.JTextField nvBH;
    private javax.swing.JButton tathoadon;
    private javax.swing.JTextField tenKH;
    private javax.swing.JTextField totalCost;
    // End of variables declaration//GEN-END:variables
}
