
package view.NhanVien;

import controller.*;
import exception.SaiSDT;
import exception.SaiSoDuong;
import exception.SaiTen;
import model.*;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MeoMeo
 * @author DinhGi
 */
public class addCustomer extends javax.swing.JPanel {

    private Connection con = ConnectDB.getConnection();
    private ArrayList<KhachHang> ds;
    private DefaultTableModel bang;
    
    public addCustomer() {
        initComponents();
        ds = new ArrayList<>();
        ds.addAll(AccessData.loadListKhachHang(con));
        bang = new DefaultTableModel(new String[] {"Tên", "Số điện thoại", "Điểm", "Hạng"}, 0);
        addCustomerTable.setModel(bang);
        for( KhachHang kh : ds)
            bang.addRow(kh.toObject());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        addCustomerTable = new javax.swing.JTable();
        tenKh = new javax.swing.JTextField();
        sdt = new javax.swing.JTextField();
        point = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        thongbao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(208, 230, 229));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1010, 506));
        setLayout(null);

        addCustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên", "Số điện thoại", "Điểm", "Hạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        addCustomerTable.setFillsViewportHeight(true);
        addCustomerTable.setSelectionBackground(new java.awt.Color(136, 161, 166));
        jScrollPane1.setViewportView(addCustomerTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(60, 90, 526, 388);

        tenKh.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(tenKh);
        tenKh.setBounds(720, 147, 275, 40);

        sdt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(sdt);
        sdt.setBounds(720, 232, 275, 40);

        point.setEditable(false);
        point.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        point.setText("0");
        add(point);
        point.setBounds(720, 319, 275, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Tên:");
        add(jLabel1);
        jLabel1.setBounds(600, 160, 37, 22);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Số điện thoại:");
        add(jLabel5);
        jLabel5.setBounds(600, 240, 113, 22);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Điểm:");
        add(jLabel7);
        jLabel7.setBounds(610, 330, 46, 22);

        cancelButton.setBackground(new java.awt.Color(233, 67, 99));
        cancelButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelIcon.png"))); // NOI18N
        cancelButton.setText("Hủy");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        add(cancelButton);
        cancelButton.setBounds(890, 380, 100, 50);

        updateButton.setBackground(new java.awt.Color(25, 191, 133));
        updateButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/updateIcon.png"))); // NOI18N
        updateButton.setText("Cập nhập");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton);
        updateButton.setBounds(720, 380, 150, 50);

        thongbao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        thongbao.setForeground(new java.awt.Color(255, 0, 0));
        add(thongbao);
        thongbao.setBounds(600, 440, 380, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 16, 74));
        jLabel2.setText("Thêm khách hàng");
        add(jLabel2);
        jLabel2.setBounds(60, 10, 340, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Borreder/addCustomerBG.png"))); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(0, 0, 1010, 530);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        tenKh.setText("");
        sdt.setText("");
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try{
            String ten = tenKh.getText();
            char c = ten.charAt(0);
            if(!ten.matches("[^0-9]{1,}")) throw new SaiTen();
            int sodt = Integer.parseInt(sdt.getText());
            if( sodt < 10000000 || sodt > 100000000) throw new exception.SaiSDT();
            int diem = Integer.parseInt(point.getText());
            if( diem < 0) throw new exception.SaiSoDuong();
            KhachHang moi = new KhachHang(sodt, ten, diem);
            if(ds.contains(moi)){
                thongbao.setText("Số đã được đăng kí!");

            }else{
                thongbao.setText("Đăng kí thành công!");
                ds.add(moi);
                bang.addRow(moi.toObject());
                AccessData.insertKhachHang(moi, con);
            }
        }catch( NumberFormatException | StringIndexOutOfBoundsException | SaiSDT | SaiSoDuong| SaiTen  ex){
            JOptionPane.showMessageDialog(null, "Nhập sai!");
        }finally{
            sdt.setText("");
            tenKh.setText("");
            thongbao.setText("");
        }
                

        
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable addCustomerTable;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField point;
    private javax.swing.JTextField sdt;
    private javax.swing.JTextField tenKh;
    private javax.swing.JLabel thongbao;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
