
package view.NhanVien;

import controller.AccessData;
import controller.ConnectDB;
import java.sql.Connection;
import model.NhanVien;

/**
 *
 * @author MeoMeo
 * @author DinhGi
 */
public class changePassForm extends javax.swing.JPanel {

    private Connection con = ConnectDB.getConnection();
    private NhanVien nhanvien;
    
    public changePassForm() {
        nhanvien = NhanVienForm.formNV.getNhanvien();
        initComponents();
        taiKhoanField.setText(nhanvien.getMa());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        taiKhoanField = new javax.swing.JTextField();
        currentPass = new javax.swing.JPasswordField();
        newPass = new javax.swing.JPasswordField();
        confirmNewPass = new javax.swing.JPasswordField();
        saveButton = new javax.swing.JButton();
        thongbao = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 102));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(785, 512));
        setLayout(null);

        jLabel2.setBackground(new java.awt.Color(38, 37, 43));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("  Thông tin cá nhân");
        add(jLabel2);
        jLabel2.setBounds(100, 80, 1030, 73);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tài khoản");
        add(jLabel6);
        jLabel6.setBounds(60, 180, 218, 47);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mật khẩu");
        add(jLabel4);
        jLabel4.setBounds(60, 300, 99, 28);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mật khẩu mới");
        add(jLabel7);
        jLabel7.setBounds(430, 180, 179, 28);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Xác nhận lại mật khẩu");
        add(jLabel8);
        jLabel8.setBounds(430, 300, 254, 28);

        taiKhoanField.setEditable(false);
        taiKhoanField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(taiKhoanField);
        taiKhoanField.setBounds(60, 220, 254, 41);

        currentPass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(currentPass);
        currentPass.setBounds(60, 340, 254, 43);

        newPass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(newPass);
        newPass.setBounds(430, 220, 254, 43);

        confirmNewPass.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        add(confirmNewPass);
        confirmNewPass.setBounds(430, 340, 254, 43);

        saveButton.setBackground(new java.awt.Color(78, 188, 100));
        saveButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/saveIcon.png"))); // NOI18N
        saveButton.setText("Lưu");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton);
        saveButton.setBounds(63, 416, 119, 50);

        thongbao.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        thongbao.setForeground(new java.awt.Color(255, 204, 204));
        add(thongbao);
        thongbao.setBounds(220, 420, 470, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Borreder/changePassBG.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 785, 532);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String mkcu = new String(currentPass.getPassword());
        String mkdoi = new String(newPass.getPassword());
        String mklai = new String(confirmNewPass.getPassword());
        thongbao.setText("");
        
        if(!mkcu.equals(AccessData.findTaiKhoan(nhanvien.getMa(), con)))
            thongbao.setText("Sai mật khẩu ");
        else if( !mkdoi.equals(mklai))
            thongbao.setText("Mật khẩu mói không khớp!");
        else{
            thongbao.setText("Đổi mật khẩu thành công!");
            AccessData.updateTaiKhoan(nhanvien.getMa(), mkdoi, con);
        }
        
        currentPass.setText("");
        newPass.setText("");
        confirmNewPass.setText("");
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmNewPass;
    private javax.swing.JPasswordField currentPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField taiKhoanField;
    private javax.swing.JLabel thongbao;
    // End of variables declaration//GEN-END:variables
}
