
package view.NhanVien;

import controller.AccessData;
import controller.ConnectDB;
import java.awt.Button;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import model.NhanVien;
import run.Login;

/**
 *
 * @author MeoMeo
 * @author DinhGi
 */
public class NhanVienForm extends javax.swing.JFrame {

    private NhanVien nhanvien;
    public static NhanVienForm formNV;
    Connection con = ConnectDB.getConnection();
    
    public NhanVienForm(String ma) {
        formNV = this;
        nhanvien = AccessData.findNhanVien(ma, con);
        initComponents();
        nameWorker.setText(nhanvien.getTen());
        DateWork.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        ktraTonKButtonShadow.setVisible(false);
        addCustomerButtonShadow.setVisible(false);
        changePassButtonShadow.setVisible(false);
        creatBillButtonShadow.setVisible(false);
        tonKhoForm1.setVisible(false);
        createBillForm2.setVisible(false);
        changePassForm2.setVisible(false);
        addCustomer2.setVisible(false);
        this.setSize(1350, 727);
        this.setLocationRelativeTo(null);
        
    }
    
    public NhanVien getNhanvien() {
        return nhanvien;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ahihihihihi = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        ktraTonKButtonShadow = new javax.swing.JButton();
        ktraTonKButton = new javax.swing.JButton();
        creatBillButtonShadow = new javax.swing.JButton();
        creatBillButton = new javax.swing.JButton();
        addCustomerButtonShadow = new javax.swing.JButton();
        addCustomerButton = new javax.swing.JButton();
        changePassButtonShadow = new javax.swing.JButton();
        changePassButton = new javax.swing.JButton();
        DateWork = new javax.swing.JTextField();
        nameWorker = new javax.swing.JTextField();
        tonKhoForm1 = new view.NhanVien.tonKhoForm();
        createBillForm2 = new view.NhanVien.createBillForm();
        changePassForm2 = new view.NhanVien.changePassForm();
        addCustomer2 = new view.NhanVien.addCustomer();
        timeWork = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        ahihihihihi.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        ahihihihihi.setForeground(new java.awt.Color(255, 255, 255));
        ahihihihihi.setText("BreadPlanetEmployee   ");
        ahihihihihi.setMaximumSize(new java.awt.Dimension(398, 70));
        ahihihihihi.setMinimumSize(new java.awt.Dimension(398, 70));
        ahihihihihi.setPreferredSize(new java.awt.Dimension(398, 70));
        getContentPane().add(ahihihihihi);
        ahihihihihi.setBounds(20, 20, 510, 70);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/closeButton.png"))); // NOI18N
        exitButton.setBorderPainted(false);
        exitButton.setContentAreaFilled(false);
        exitButton.setFocusPainted(false);
        exitButton.setFocusable(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        getContentPane().add(exitButton);
        exitButton.setBounds(1270, 20, 67, 60);

        ktraTonKButtonShadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/ktraTonKButtonShadow.png"))); // NOI18N
        ktraTonKButtonShadow.setBorderPainted(false);
        ktraTonKButtonShadow.setContentAreaFilled(false);
        ktraTonKButtonShadow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ktraTonKButtonShadowMouseClicked(evt);
            }
        });
        getContentPane().add(ktraTonKButtonShadow);
        ktraTonKButtonShadow.setBounds(10, 140, 290, 81);

        ktraTonKButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/ktraTonKButton.png"))); // NOI18N
        ktraTonKButton.setBorderPainted(false);
        ktraTonKButton.setContentAreaFilled(false);
        ktraTonKButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ktraTonKButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ktraTonKButton);
        ktraTonKButton.setBounds(20, 160, 250, 50);

        creatBillButtonShadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/createBillButtonShadow.png"))); // NOI18N
        creatBillButtonShadow.setBorderPainted(false);
        creatBillButtonShadow.setContentAreaFilled(false);
        creatBillButtonShadow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creatBillButtonShadowMouseClicked(evt);
            }
        });
        getContentPane().add(creatBillButtonShadow);
        creatBillButtonShadow.setBounds(10, 220, 290, 80);

        creatBillButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/createBillButton.png"))); // NOI18N
        creatBillButton.setBorderPainted(false);
        creatBillButton.setContentAreaFilled(false);
        creatBillButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creatBillButtonMouseClicked(evt);
            }
        });
        getContentPane().add(creatBillButton);
        creatBillButton.setBounds(20, 230, 250, 60);

        addCustomerButtonShadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/addCustomerButtonShadow.png"))); // NOI18N
        addCustomerButtonShadow.setBorderPainted(false);
        addCustomerButtonShadow.setContentAreaFilled(false);
        addCustomerButtonShadow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerButtonShadowMouseClicked(evt);
            }
        });
        getContentPane().add(addCustomerButtonShadow);
        addCustomerButtonShadow.setBounds(10, 300, 290, 90);

        addCustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/addCustomerButton.png"))); // NOI18N
        addCustomerButton.setBorderPainted(false);
        addCustomerButton.setContentAreaFilled(false);
        addCustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerButtonMouseClicked(evt);
            }
        });
        getContentPane().add(addCustomerButton);
        addCustomerButton.setBounds(20, 320, 250, 60);

        changePassButtonShadow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/changePassButtonShadow.png"))); // NOI18N
        changePassButtonShadow.setBorderPainted(false);
        changePassButtonShadow.setContentAreaFilled(false);
        changePassButtonShadow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePassButtonShadowMouseClicked(evt);
            }
        });
        getContentPane().add(changePassButtonShadow);
        changePassButtonShadow.setBounds(0, 400, 310, 70);

        changePassButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/changePassButton.png"))); // NOI18N
        changePassButton.setBorderPainted(false);
        changePassButton.setContentAreaFilled(false);
        changePassButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changePassButtonMouseClicked(evt);
            }
        });
        getContentPane().add(changePassButton);
        changePassButton.setBounds(20, 410, 250, 50);

        DateWork.setBackground(new java.awt.Color(204, 204, 255));
        DateWork.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        DateWork.setText("Date");
        DateWork.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        DateWork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateWorkActionPerformed(evt);
            }
        });
        getContentPane().add(DateWork);
        DateWork.setBounds(50, 660, 190, 30);

        nameWorker.setBackground(new java.awt.Color(204, 204, 255));
        nameWorker.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nameWorker.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameWorker.setText("TenNV");
        nameWorker.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        nameWorker.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        nameWorker.setDisabledTextColor(new java.awt.Color(255, 102, 102));
        getContentPane().add(nameWorker);
        nameWorker.setBounds(50, 550, 190, 70);
        getContentPane().add(tonKhoForm1);
        tonKhoForm1.setBounds(360, 170, 1004, 577);
        getContentPane().add(createBillForm2);
        createBillForm2.setBounds(300, 140, 1018, 558);
        getContentPane().add(changePassForm2);
        changePassForm2.setBounds(400, 120, 785, 540);
        getContentPane().add(addCustomer2);
        addCustomer2.setBounds(300, 160, 1010, 530);

        timeWork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/TimeWorkTable.png"))); // NOI18N
        getContentPane().add(timeWork);
        timeWork.setBounds(30, 500, 227, 204);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Borreder/nvBG.png"))); // NOI18N
        BG.setPreferredSize(new java.awt.Dimension(1350, 725));
        getContentPane().add(BG);
        BG.setBounds(0, 0, 1350, 725);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        this.dispose();
        Login.loginform.setVisible(true);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void ktraTonKButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ktraTonKButtonMouseClicked
        ktraTonKButtonShadow.setVisible(true);
        ktraTonKButton.setVisible(false);
        tonKhoForm.khoform.updateData();
        tonKhoForm1.setVisible(true);
        addCustomerButtonShadow.setVisible(false);
        changePassButtonShadow.setVisible(false);
        creatBillButtonShadow.setVisible(false);
        addCustomerButton.setVisible(true);
        changePassButton.setVisible(true);
        creatBillButton.setVisible(true);
        createBillForm2.setVisible(false);
        changePassForm2.setVisible(false);
        addCustomer2.setVisible(false);
        
    }//GEN-LAST:event_ktraTonKButtonMouseClicked

    private void changePassButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePassButtonMouseClicked
        changePassButtonShadow.setVisible(true);
        changePassButton.setVisible(false);
        changePassForm2.setVisible(true);
        ktraTonKButtonShadow.setVisible(false);
        addCustomerButtonShadow.setVisible(false);
        creatBillButtonShadow.setVisible(false);
        ktraTonKButton.setVisible(true);
        addCustomerButton.setVisible(true);
        creatBillButton.setVisible(true);
        tonKhoForm1.setVisible(false);
        createBillForm2.setVisible(false);
        addCustomer2.setVisible(false);
        
    }//GEN-LAST:event_changePassButtonMouseClicked

    private void changePassButtonShadowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changePassButtonShadowMouseClicked
        changePassButtonShadow.setVisible(false);
        changePassButton.setVisible(true);
        changePassForm2.setVisible(false);
    }//GEN-LAST:event_changePassButtonShadowMouseClicked

    private void addCustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerButtonMouseClicked
        addCustomerButtonShadow.setVisible(true);
        addCustomerButton.setVisible(false);
        addCustomer2.setVisible(true);
        ktraTonKButtonShadow.setVisible(false);
        changePassButtonShadow.setVisible(false);
        creatBillButtonShadow.setVisible(false);
        ktraTonKButton.setVisible(true);
        changePassButton.setVisible(true);
        creatBillButton.setVisible(true);
        tonKhoForm1.setVisible(false);
        createBillForm2.setVisible(false);
        changePassForm2.setVisible(false);
    }//GEN-LAST:event_addCustomerButtonMouseClicked

    private void addCustomerButtonShadowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerButtonShadowMouseClicked
        addCustomerButtonShadow.setVisible(false);
        addCustomerButton.setVisible(true);
        addCustomer2.setVisible(false);
    }//GEN-LAST:event_addCustomerButtonShadowMouseClicked

    private void creatBillButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatBillButtonMouseClicked
        creatBillButtonShadow.setVisible(true);
        createBillForm.billform.updateData();
        creatBillButton.setVisible(false);
        createBillForm2.setVisible(true);
        ktraTonKButtonShadow.setVisible(false);
        addCustomerButtonShadow.setVisible(false);
        changePassButtonShadow.setVisible(false);
        ktraTonKButton.setVisible(true);
        addCustomerButton.setVisible(true);
        changePassButton.setVisible(true);
        tonKhoForm1.setVisible(false);
        changePassForm2.setVisible(false);
        addCustomer2.setVisible(false);
    }//GEN-LAST:event_creatBillButtonMouseClicked

    private void creatBillButtonShadowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creatBillButtonShadowMouseClicked
        creatBillButtonShadow.setVisible(false);
        creatBillButton.setVisible(true);
        createBillForm2.setVisible(false);
    }//GEN-LAST:event_creatBillButtonShadowMouseClicked

    private void DateWorkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateWorkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateWorkActionPerformed

    private void ktraTonKButtonShadowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ktraTonKButtonShadowMouseClicked
        ktraTonKButtonShadow.setVisible(false);
        ktraTonKButton.setVisible(true);
        tonKhoForm1.setVisible(false);
    }//GEN-LAST:event_ktraTonKButtonShadowMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NhanVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NhanVienForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JTextField DateWork;
    private view.NhanVien.addCustomer addCustomer2;
    private javax.swing.JButton addCustomerButton;
    private javax.swing.JButton addCustomerButtonShadow;
    private javax.swing.JLabel ahihihihihi;
    private javax.swing.JButton changePassButton;
    private javax.swing.JButton changePassButtonShadow;
    private view.NhanVien.changePassForm changePassForm2;
    private javax.swing.JButton creatBillButton;
    private javax.swing.JButton creatBillButtonShadow;
    private view.NhanVien.createBillForm createBillForm2;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton ktraTonKButton;
    private javax.swing.JButton ktraTonKButtonShadow;
    private javax.swing.JTextField nameWorker;
    private javax.swing.JLabel timeWork;
    private view.NhanVien.tonKhoForm tonKhoForm1;
    // End of variables declaration//GEN-END:variables
}
