
package view.NhanVien;

import controller.ConnectDB;
import controller.QueryReport;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author MeoMeo
 * @author DinhGi
 */
public class tonKhoForm extends javax.swing.JPanel {

    private Connection con = ConnectDB.getConnection();
    private TableRowSorter<TableModel> sorter ;
    boolean sx ;
    public static tonKhoForm  khoform;
    
    public tonKhoForm() {
        initComponents();
        khoform = this;
        updateData();
        sorter = new TableRowSorter<>(thongTinKhoTable.getModel());
        thongTinKhoTable.setRowSorter(sorter);
        sx = false;
    }
    
    public void updateData(){
        
        thongTinKhoTable.setModel(QueryReport.reportTonKho(con));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        thongTinKhoTable = new javax.swing.JTable();
        sapxep = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(120, 213, 245));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1004, 577));
        setLayout(null);

        thongTinKhoTable.setBackground(new java.awt.Color(237, 247, 246));
        thongTinKhoTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        thongTinKhoTable.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        thongTinKhoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã bánh", "Tên bánh", "Loại bánh", "Số lượng tồn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        thongTinKhoTable.setFillsViewportHeight(true);
        thongTinKhoTable.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jScrollPane1.setViewportView(thongTinKhoTable);
        if (thongTinKhoTable.getColumnModel().getColumnCount() > 0) {
            thongTinKhoTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            thongTinKhoTable.getColumnModel().getColumn(1).setPreferredWidth(2);
            thongTinKhoTable.getColumnModel().getColumn(2).setPreferredWidth(2);
            thongTinKhoTable.getColumnModel().getColumn(3).setPreferredWidth(2);
        }

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 120, 510, 320);

        sapxep.setBackground(new java.awt.Color(235, 96, 117));
        sapxep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sapxep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sortButton.png"))); // NOI18N
        sapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapxepActionPerformed(evt);
            }
        });
        add(sapxep);
        sapxep.setBounds(540, 120, 50, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Thông tin tồn kho");
        add(jLabel1);
        jLabel1.setBounds(30, 20, 540, 56);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Borreder/tonKhoGB1.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1053, 573);
    }// </editor-fold>//GEN-END:initComponents

    private void sapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapxepActionPerformed

        if(!sx){
            sorter.setSortable(3, true);
            ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>();
            sortKeys.add(new RowSorter.SortKey(3, SortOrder.DESCENDING));
            sorter.setSortKeys(sortKeys);
            sorter.sort();
            sx = true;
        }
        else{
            sorter.setSortable(3, false);
            thongTinKhoTable.setModel(QueryReport.reportTonKho(con));
            sx = false;
        }
        
    }//GEN-LAST:event_sapxepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sapxep;
    private javax.swing.JTable thongTinKhoTable;
    // End of variables declaration//GEN-END:variables
}
