
package view.QuanLy;

import controller.* ;
import exception.SaiSoDuong;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.BanhMi;


/**
 *
 * @author MeoMeo
 * @author DinhGi
 */
public class qlKhoForm extends javax.swing.JPanel implements ItemListener{

    Connection con = ConnectDB.getConnection();
    ArrayList <BanhMi> ds, banh;
    TableRowSorter<TableModel> sorter ;
    public static qlKhoForm khoform;
    boolean sx ;
    
    public qlKhoForm() {
        initComponents();
        khoform = this;
        ds = new ArrayList<>();
        ngayNhap.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date().getTime()));
        maPhieu.setText((new Date().getTime() ) + "");
        loaiBanh.removeAllItems();
        tenBanh.removeAllItems();
        for( int i = 0 ; i < BanhMi.cacloai.length; i++)
             loaiBanh.addItem(BanhMi.cacloai[i]);
        loaiBanh.addItemListener(this);
        
    }
    
    @Override
    public void itemStateChanged(ItemEvent e) {
        if(e.getSource() == loaiBanh){
            banh = AccessData.loadListBanhMi(con);
            tenBanh.removeAllItems();
            ds.clear();
            String loai = loaiBanh.getSelectedItem().toString();
            for( BanhMi b : banh)
                if( loai.equals(b.getLoai())){
                    ds.add(b);
                    tenBanh.addItem(b.getTen());
                }     
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nhapKhoPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ngayNhap = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loaiBanh = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        tenBanh = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        soLuong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        maPhieu = new javax.swing.JTextField();
        huy = new javax.swing.JButton();
        xacnhan = new javax.swing.JButton();
        thongbao = new javax.swing.JLabel();
        kiemKhoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        thongTinKhoTable = new javax.swing.JTable();
        sapxep = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setPreferredSize(new java.awt.Dimension(766, 530));
        setLayout(null);

        nhapKhoPanel.setBackground(new java.awt.Color(170, 201, 206));
        nhapKhoPanel.setToolTipText("");
        nhapKhoPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        nhapKhoPanel.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        nhapKhoPanel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(222, 229, 230));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Ngày nhập:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 90, 150, 60);

        ngayNhap.setEditable(false);
        ngayNhap.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(ngayNhap);
        ngayNhap.setBounds(200, 100, 250, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Loại bánh:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 230, 140, 60);

        loaiBanh.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        loaiBanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(loaiBanh);
        loaiBanh.setBounds(200, 240, 250, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Tên bánh:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 300, 120, 60);

        tenBanh.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tenBanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(tenBanh);
        tenBanh.setBounds(200, 310, 250, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Số lượng:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 380, 130, 60);

        soLuong.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(soLuong);
        soLuong.setBounds(200, 380, 250, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setText("Mã phiếu:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 160, 150, 60);

        maPhieu.setEditable(false);
        maPhieu.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(maPhieu);
        maPhieu.setBounds(200, 170, 250, 30);

        huy.setBackground(new java.awt.Color(244, 44, 88));
        huy.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelIcon.png"))); // NOI18N
        huy.setText("Hủy");
        huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyActionPerformed(evt);
            }
        });
        jPanel1.add(huy);
        huy.setBounds(630, 370, 100, 50);

        xacnhan.setBackground(new java.awt.Color(30, 202, 70));
        xacnhan.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        xacnhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/yesIcon.png"))); // NOI18N
        xacnhan.setText("Xác nhận");
        xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xacnhanActionPerformed(evt);
            }
        });
        jPanel1.add(xacnhan);
        xacnhan.setBounds(470, 370, 150, 50);

        thongbao.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        thongbao.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(thongbao);
        thongbao.setBounds(60, 440, 390, 30);

        nhapKhoPanel.addTab("Nhập kho", jPanel1);

        kiemKhoPanel.setBackground(new java.awt.Color(232, 238, 239));
        kiemKhoPanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                kiemKhoPanelComponentShown(evt);
            }
        });
        kiemKhoPanel.setLayout(null);

        thongTinKhoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã bánh", "Tên bánh", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        thongTinKhoTable.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(thongTinKhoTable);

        kiemKhoPanel.add(jScrollPane1);
        jScrollPane1.setBounds(20, 60, 700, 410);

        sapxep.setBackground(new java.awt.Color(235, 74, 115));
        sapxep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/sortButton.png"))); // NOI18N
        sapxep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sapxepActionPerformed(evt);
            }
        });
        kiemKhoPanel.add(sapxep);
        sapxep.setBounds(670, 20, 50, 40);

        nhapKhoPanel.addTab("Kiểm kho", kiemKhoPanel);

        add(nhapKhoPanel);
        nhapKhoPanel.setBounds(10, 0, 750, 520);
    }// </editor-fold>//GEN-END:initComponents

    private void xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xacnhanActionPerformed
        try{
            String ma = maPhieu.getText();
            int soluong = Integer.parseInt(soLuong.getText());
            if(soluong <= 0) throw new exception.SaiSoDuong();
            AccessData.insertPhieuNhapKho(ma,ds.get(tenBanh.getSelectedIndex()).getMa()
                                    ,soluong,con);
            maPhieu.setText((new Date().getTime()) + "");
            //new in phieu
        }catch( StringIndexOutOfBoundsException | NumberFormatException | SaiSoDuong ex){
            JOptionPane.showMessageDialog(null, "Nhập sai!");
        }finally{
            soLuong.setText("");
        }   
    }//GEN-LAST:event_xacnhanActionPerformed

    private void huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyActionPerformed
        soLuong.setText("");
    }//GEN-LAST:event_huyActionPerformed

    private void kiemKhoPanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_kiemKhoPanelComponentShown
        thongTinKhoTable.setModel(QueryReport.reportTonKho(con));
        sorter = new TableRowSorter<>(thongTinKhoTable.getModel());
        thongTinKhoTable.setRowSorter(sorter);
        sx = false;
    }//GEN-LAST:event_kiemKhoPanelComponentShown

    private void sapxepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sapxepActionPerformed
        if(!sx){
            sorter.setSortable(3, true);
            ArrayList<RowSorter.SortKey> sortKeys = new ArrayList<>();
            sortKeys.add(new RowSorter.SortKey(3, SortOrder.DESCENDING));
            sorter.setSortKeys(sortKeys);
            sorter.sort();
            sx = true;
        }
        else{
            sorter.setSortable(3, false);
            thongTinKhoTable.setModel(QueryReport.reportTonKho(con));
            sx = false;
        }
    }//GEN-LAST:event_sapxepActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton huy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel kiemKhoPanel;
    private javax.swing.JComboBox<String> loaiBanh;
    private javax.swing.JTextField maPhieu;
    private javax.swing.JTextField ngayNhap;
    private javax.swing.JTabbedPane nhapKhoPanel;
    private javax.swing.JButton sapxep;
    private javax.swing.JTextField soLuong;
    private javax.swing.JComboBox<String> tenBanh;
    private javax.swing.JTable thongTinKhoTable;
    private javax.swing.JLabel thongbao;
    private javax.swing.JButton xacnhan;
    // End of variables declaration//GEN-END:variables

    
}
