
package view.QuanLy;

import controller.ConnectDB;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import model.BanhMi;
import model.ChiTietDon;
import model.HoaDon;

/**
 *
 * @author MeoMeo
 * @author DinhGi
 */
public class qlOrderForm extends javax.swing.JPanel {

    Connection con = ConnectDB.getConnection();
    ArrayList<HoaDon> dshd ;
    HashMap <BanhMi, Integer> cap ;
    DefaultTableModel banghd;
    DefaultTableModel chitiet;
    DefaultTableModel bangxuat;
    
    public qlOrderForm() {
        initComponents();
        ngayXuatTextField.setText(new SimpleDateFormat("dd/MM/yyyy").format(new Date()));
        chitiet = new DefaultTableModel(new String[] {"Mã bánh","Tên bánh", "Số lượng"},0);
        banghd = new DefaultTableModel(new String[] {"Mã đơn", "Tên nhân viên", "Tên khách", "Chiết khấu(%)", "Trị giá", "Thời gian"} , 0);
        bangxuat = new DefaultTableModel(new String[] {"Mã bánh","Tên bánh", "Số lượng"},0);
        xuatKhoTable.setModel(bangxuat);
        chiTietTable.setModel(chitiet);
        donHangTable.setModel(banghd);
        donHangTable.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        cap = new HashMap<>();
        updateData();
    }
    
    private void update(){
        duyetDonButton.setEnabled(true);
        xoaDonButtton.setEnabled(false);
        xuatKhoButton.setEnabled(false);
        huy.setEnabled(false);
    }
    
    public  void updateData(){
        dshd = controller.AccessData.loadListHoaDon(con);
        xoaBang();
        for( HoaDon h : dshd)
            banghd.addRow(h.toObject());
        
    }
    
    private void xoaBang(){
        while(banghd.getRowCount() != 0)
            banghd.removeRow(0);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thongbao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donHangTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        chiTietTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        duyetDonButton = new javax.swing.JButton();
        huy = new javax.swing.JButton();
        xoaDonButtton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        xuatKhoTable = new javax.swing.JTable();
        xuatKhoButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ngayXuatTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 206, 199));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(990, 530));
        setLayout(null);

        thongbao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        thongbao.setForeground(new java.awt.Color(255, 0, 0));
        add(thongbao);
        thongbao.setBounds(520, 260, 450, 40);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        donHangTable.setBackground(new java.awt.Color(246, 218, 169));
        donHangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã đơn", "Tên nhân viên", "Tên khách hàng", "Chiết khấu", "Tiền", "Thời gian"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        donHangTable.setFillsViewportHeight(true);
        donHangTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                donHangTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(donHangTable);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 590, 190);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Đơn hàng");
        add(jLabel1);
        jLabel1.setBounds(30, 20, 120, 30);

        jScrollPane2.setBorder(null);
        jScrollPane2.setOpaque(false);

        chiTietTable.setBackground(new java.awt.Color(246, 218, 169));
        chiTietTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tên bánh", "ma banh", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        chiTietTable.setFillsViewportHeight(true);
        jScrollPane2.setViewportView(chiTietTable);

        add(jScrollPane2);
        jScrollPane2.setBounds(644, 50, 320, 190);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Chi tiết đơn");
        add(jLabel2);
        jLabel2.setBounds(650, 20, 190, 30);

        duyetDonButton.setBackground(new java.awt.Color(33, 193, 168));
        duyetDonButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        duyetDonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/yesIcon.png"))); // NOI18N
        duyetDonButton.setText("Duyệt đơn");
        duyetDonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duyetDonButtonActionPerformed(evt);
            }
        });
        add(duyetDonButton);
        duyetDonButton.setBounds(520, 300, 190, 60);

        huy.setBackground(new java.awt.Color(230, 78, 103));
        huy.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        huy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelIcon.png"))); // NOI18N
        huy.setText("Hủy");
        huy.setEnabled(false);
        huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huyActionPerformed(evt);
            }
        });
        add(huy);
        huy.setBounds(690, 460, 120, 50);

        xoaDonButtton.setBackground(new java.awt.Color(230, 78, 103));
        xoaDonButtton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        xoaDonButtton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/cancelIcon.png"))); // NOI18N
        xoaDonButtton.setText("Xóa đơn");
        xoaDonButtton.setEnabled(false);
        xoaDonButtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaDonButttonActionPerformed(evt);
            }
        });
        add(xoaDonButtton);
        xoaDonButtton.setBounds(740, 300, 170, 60);

        jScrollPane3.setBorder(null);
        jScrollPane3.setOpaque(false);

        xuatKhoTable.setBackground(new java.awt.Color(246, 218, 169));
        xuatKhoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã bánh", "Tên bánh", "Số lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        xuatKhoTable.setFillsViewportHeight(true);
        jScrollPane3.setViewportView(xuatKhoTable);

        add(jScrollPane3);
        jScrollPane3.setBounds(30, 290, 450, 220);

        xuatKhoButton.setBackground(new java.awt.Color(215, 153, 25));
        xuatKhoButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        xuatKhoButton.setText("Xuất kho");
        xuatKhoButton.setEnabled(false);
        xuatKhoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xuatKhoButtonActionPerformed(evt);
            }
        });
        add(xuatKhoButton);
        xuatKhoButton.setBounds(520, 460, 130, 50);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Xuất kho");
        add(jLabel3);
        jLabel3.setBounds(30, 260, 140, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel4.setText("Ngày xuất:");
        add(jLabel4);
        jLabel4.setBounds(520, 400, 120, 40);

        ngayXuatTextField.setEditable(false);
        ngayXuatTextField.setBackground(new java.awt.Color(204, 204, 255));
        ngayXuatTextField.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        add(ngayXuatTextField);
        ngayXuatTextField.setBounds(660, 390, 310, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Borreder/orderBG.png"))); // NOI18N
        add(jLabel5);
        jLabel5.setBounds(0, 0, 991, 531);
    }// </editor-fold>//GEN-END:initComponents

    private void duyetDonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duyetDonButtonActionPerformed
        dshd = controller.AccessData.loadListHoaDon(con);
        ArrayList<ChiTietDon> ds ;
        BanhMi b;
        int old = 0;
        for( HoaDon h : dshd){
            ds = h.getDsBanh();
            for( ChiTietDon c : ds){
                b = c.getBanh();
                if(cap.containsKey(b)){
                    old = cap.get(b); 
                    cap.replace(b, old, old +  c.getSoluong());
                }   
                else{
                    cap.put(b, c.getSoluong());
                }
            }      
        }
        int row = 0;
        bangxuat.setRowCount(cap.size());
        for (BanhMi key : cap.keySet()) {
            bangxuat.setValueAt(key.getMa(), row, 0);
            bangxuat.setValueAt(key.getTen(), row, 1);
            bangxuat.setValueAt(cap.get(key), row, 2);
            row++;
         }
        xuatKhoButton.setEnabled(true); 
        huy.setEnabled(true);
        xoaBang();
         while(chitiet.getRowCount() != 0)
            chitiet.removeRow(0);
    }//GEN-LAST:event_duyetDonButtonActionPerformed

    private void huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huyActionPerformed
        while(bangxuat.getRowCount() != 0)
            bangxuat.removeRow(0);
        updateData();
        cap.clear();
        update();
        
    }//GEN-LAST:event_huyActionPerformed

    private void donHangTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_donHangTableMouseClicked
        int row = donHangTable.getSelectedRow();
        if(row < 0 || row >= banghd.getRowCount())
            return;
        String ma = banghd.getValueAt(row, 0).toString();
        ArrayList<ChiTietDon> ds = controller.AccessData.loadListChiTietDon(ma, con);
        chitiet.setRowCount(ds.size());
        int i = 0;
        for(ChiTietDon c: ds){
            chitiet.setValueAt(c.getBanh().getMa(),i,0 );
            chitiet.setValueAt(c.getBanh().getTen(),i, 1);
            chitiet.setValueAt(c.getSoluong(),i, 2);
            i++;
        }
        xoaDonButtton.setEnabled(true);
    }//GEN-LAST:event_donHangTableMouseClicked

    private void xoaDonButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaDonButttonActionPerformed
        int row = donHangTable.getSelectedRow();
        String ma = banghd.getValueAt(row, 0).toString();
        controller.AccessData.deleteHoaDon(ma, con);
       // donHangTable.removeRowSelectionInterval(row, row);
        banghd.removeRow(row);
        while(chitiet.getRowCount() != 0)
            chitiet.removeRow(0);
        xoaDonButtton.setEnabled(false);
        thongbao.setText("*Xóa đơn!");
        
    }//GEN-LAST:event_xoaDonButttonActionPerformed

    private void xuatKhoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xuatKhoButtonActionPerformed
        String ma = new Date().getTime() + "";
        while(bangxuat.getRowCount() != 0)
            bangxuat.removeRow(0);
        for (BanhMi key : cap.keySet()){
            controller.AccessData.insertPhieuXuatKho(ma, key.getMa(),cap.get(key), con);
        }
        dshd = controller.AccessData.loadListHoaDon(con);
        for(HoaDon h : dshd)
            controller.AccessData.updateTrangThaiHoadon(h.getMa(), con);
        cap.clear();
        thongbao.setText("*Xuất kho!");
        update();
    }//GEN-LAST:event_xuatKhoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable chiTietTable;
    private javax.swing.JTable donHangTable;
    private javax.swing.JButton duyetDonButton;
    private javax.swing.JButton huy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField ngayXuatTextField;
    private javax.swing.JLabel thongbao;
    private javax.swing.JButton xoaDonButtton;
    private javax.swing.JButton xuatKhoButton;
    private javax.swing.JTable xuatKhoTable;
    // End of variables declaration//GEN-END:variables
}
