
package run;

import controller.AccessData;
import controller.ConnectDB;
import java.sql.Connection;
import javax.swing.JFrame;
import view.NhanVien.NhanVienForm;
import view.QuanLy.QuanLyForm;

/**
 *
 * @author MeoMeo
 * @author DinhGi
 */
public class Login extends javax.swing.JFrame {
    public static Login loginform;
    Connection con = ConnectDB.getConnection();
    String tk, mk;

    public Login() {
        initComponents();
        loginform = this;
        this.setSize(800,500);
        this.setLocationRelativeTo(this);//khung xuat hien giua man hinh
        errorWarning.setVisible(false);
    }
    
    private void dangNhap(){
         tk = loginField.getText();
        mk = new String(PassField.getPassword());
        String s = AccessData.findTaiKhoan(tk, con);
        if(s == null){
            errorWarning.setVisible(true);
        }
        else if( tk.equals("admin") && mk.equals(s)){
            PassField.setText("");
           new QuanLyForm().setVisible(true);
          
           errorWarning.setVisible(false);
           this.dispose();
        }
        else if( mk.equals(s)){
            PassField.setText("");
             new NhanVienForm(tk).setVisible(true);
            errorWarning.setVisible(false);
            this.dispose();
        }
        else
            errorWarning.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginField = new javax.swing.JTextField();
        TaiKhoan = new javax.swing.JLabel();
        MatKhau = new javax.swing.JLabel();
        PassField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        errorWarning = new javax.swing.JLabel();
        Theme = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        closeButton = new javax.swing.JButton();
        miniButton = new javax.swing.JButton();
        ahihihihihi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(46, 68, 84));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(46, 68, 84));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        loginField.setBackground(new java.awt.Color(204, 204, 255));
        loginField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        TaiKhoan.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TaiKhoan.setForeground(new java.awt.Color(98, 179, 162));
        TaiKhoan.setText("Tài khoản");
        TaiKhoan.setToolTipText("");

        MatKhau.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        MatKhau.setForeground(new java.awt.Color(98, 179, 162));
        MatKhau.setText("Mật khẩu");

        PassField.setBackground(new java.awt.Color(204, 204, 255));
        PassField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassFieldActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(51, 255, 137));
        LoginButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        LoginButton.setText("Đăng nhập");
        LoginButton.setToolTipText("");
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.setMinimumSize(new java.awt.Dimension(110, 110));
        LoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginButtonMouseClicked(evt);
            }
        });

        errorWarning.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        errorWarning.setForeground(new java.awt.Color(255, 51, 51));
        errorWarning.setText("Chưa nhập đúng thông tin!");
        errorWarning.setToolTipText("");

        Theme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/logoFinal.png"))); // NOI18N
        Theme.setBorderPainted(false);
        Theme.setContentAreaFilled(false);
        Theme.setFocusPainted(false);
        Theme.setFocusable(false);

        jPanel2.setBackground(new java.awt.Color(232, 81, 74));

        closeButton.setBackground(new java.awt.Color(0, 0, 0));
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/closeButton.png"))); // NOI18N
        closeButton.setAutoscrolls(true);
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButton.setFocusPainted(false);
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        miniButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/miniButton.png"))); // NOI18N
        miniButton.setBorderPainted(false);
        miniButton.setContentAreaFilled(false);
        miniButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniButton.setFocusPainted(false);
        miniButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniButtonMouseClicked(evt);
            }
        });

        ahihihihihi.setFont(new java.awt.Font("Monotype Corsiva", 1, 48)); // NOI18N
        ahihihihihi.setForeground(new java.awt.Color(255, 255, 255));
        ahihihihihi.setText("BreadPlanetCompany  ");
        ahihihihihi.setMaximumSize(new java.awt.Dimension(398, 70));
        ahihihihihi.setMinimumSize(new java.awt.Dimension(398, 70));
        ahihihihihi.setPreferredSize(new java.awt.Dimension(398, 70));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ahihihihihi, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(miniButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(closeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(miniButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ahihihihihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TaiKhoan)
                    .addComponent(MatKhau))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(errorWarning)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(115, 115, 115))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(Theme, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Theme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loginField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TaiKhoan))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MatKhau)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorWarning)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginButtonMouseClicked
        dangNhap();
           
            
    }//GEN-LAST:event_LoginButtonMouseClicked

    private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeButtonMouseClicked

    private void miniButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniButtonMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_miniButtonMouseClicked

    private void PassFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassFieldActionPerformed
        dangNhap();
    }//GEN-LAST:event_PassFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                ;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel MatKhau;
    private javax.swing.JPasswordField PassField;
    private javax.swing.JLabel TaiKhoan;
    private javax.swing.JButton Theme;
    private javax.swing.JLabel ahihihihihi;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel errorWarning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField loginField;
    private javax.swing.JButton miniButton;
    // End of variables declaration//GEN-END:variables

    
}
